// Полный словарь переводов стран EN -> RU
export const countryMap = {
  'Afghanistan': 'Афганистан',
  'Albania': 'Албания',
  'Algeria': 'Алжир',
  'Andorra': 'Андорра',
  'Anguilla': 'Ангилья',
  'Antigua': 'Антигуа',
  'Antigua and Barbuda': 'Антигуа и Барбуда',
  'Aruba': 'Аруба',
  'Bermuda': 'Бермуды',
  'British Virgin Islands': 'Британские Виргинские острова',
  'Cabo Verde': 'Кабо-Верде',
  'Caribbean Netherlands': 'Карибские Нидерланды',
  'Cayman Islands': 'Каймановы острова',
  'Channel Islands': 'Нормандские острова',
  'Cook Islands': 'Острова Кука',
  "Côte d'Ivoire": 'Кот-д’Ивуар',
  'Curaçao': 'Кюрасао',
  'Diamond Princess': 'Даймонд Принцесс',
  'DRC': 'Демократическая Республика Конго',
  'Falkland Islands (Malvinas)': 'Фолклендские острова (Мальвинские)',
  'Faroe Islands': 'Фарерские острова',
  'French Guiana': 'Французская Гвиана',
  'French Polynesia': 'Французская Полинезия',
  'Gibraltar': 'Гибралтар',
  'Greenland': 'Гренландия',
  'Guadeloupe': 'Гваделупа',
  'Holy See (Vatican City State)': 'Ватикан',
  'Hong Kong': 'Гонконг',
  'Isle of Man': 'Остров Мэн',
  "Lao People's Democratic Republic": 'Лаос',
  'Libyan Arab Jamahiriya': 'Ливия',
  'Macao': 'Макао',
  'Macedonia': 'Македония',
  'Martinique': 'Мартиника',
  'Mayotte': 'Майотта',
  'Montserrat': 'Монтсеррат',
  'MS Zaandam': 'МС Заандам',
  'N. Korea': 'Северная Корея',
  'New Caledonia': 'Новая Каледония',
  'Niue': 'Ниуэ',
  'Palestine': 'Палестина',
  'Réunion': 'Реюньон',
  'S. Korea': 'Южная Корея',
  'Saint Helena': 'Остров Святой Елены',
  'Saint Martin': 'Сен-Мартен',
  'Saint Pierre Miquelon': 'Сен-Пьер и Микелон',
  'Sint Maarten': 'Синт-Мартен',
  'St. Barth': 'Сен-Бартелеми',
  'Swaziland': 'Свазиленд',
  'Syrian Arab Republic': 'Сирия',
  'Timor-Leste': 'Восточный Тимор',
  'Tokelau': 'Токелау',
  'Turks and Caicos Islands': 'Теркс и Кайкос',
  'UAE': 'ОАЭ',
  'UK': 'Великобритания',
  'Wallis and Futuna': 'Уоллис и Футуна',
  'Western Sahara': 'Западная Сахара',
  Bahrain: 'Бахрейн',
  Bangladesh: 'Бангладеш',
  Barbados: 'Барбадос',
  Belarus: 'Беларусь',
  Belgium: 'Бельгия',
  Belize: 'Белиз',
  Benin: 'Бенин',
  Bhutan: 'Бутан',
  Bolivia: 'Боливия',
  Bosnia: 'Босния и Герцеговина',
  Botswana: 'Ботсвана',
  Brazil: 'Бразилия',
  Brunei: 'Бруней',
  Bulgaria: 'Болгария',
  'Burkina Faso': 'Буркина-Фасо',
  Burundi: 'Бурунди',
  Cambodia: 'Камбоджа',
  Cameroon: 'Камерун',
  Canada: 'Канада',
  'Cape Verde': 'Кабо-Верде',
  'Central African Republic': 'ЦАР',
  Chad: 'Чад',
  Chile: 'Чили',
  China: 'Китай',
  Colombia: 'Колумбия',
  Comoros: 'Коморы',
  Congo: 'Конго',
  'Costa Rica': 'Коста-Рика',
  Croatia: 'Хорватия',
  Cuba: 'Куба',
  Cyprus: 'Кипр',
  Czechia: 'Чехия',
  Denmark: 'Дания',
  Djibouti: 'Джибути',
  Dominica: 'Доминика',
  'Dominican Republic': 'Доминиканская Республика',
  Ecuador: 'Эквадор',
  Egypt: 'Египет',
  'El Salvador': 'Сальвадор',
  'Equatorial Guinea': 'Экваториальная Гвинея',
  Eritrea: 'Эритрея',
  Estonia: 'Эстония',
  Eswatini: 'Эсватини',
  Ethiopia: 'Эфиопия',
  Fiji: 'Фиджи',
  Finland: 'Финляндия',
  France: 'Франция',
  Gabon: 'Габон',
  Gambia: 'Гамбия',
  Georgia: 'Грузия',
  Germany: 'Германия',
  Ghana: 'Гана',
  Greece: 'Греция',
  Grenada: 'Гренада',
  Guatemala: 'Гватемала',
  Guinea: 'Гвинея',
  'Guinea-Bissau': 'Гвинея-Бисау',
  Guyana: 'Гайана',
  Haiti: 'Гаити',
  Honduras: 'Гондурас',
  Hungary: 'Венгрия',
  Iceland: 'Исландия',
  India: 'Индия',
  Indonesia: 'Индонезия',
  Iran: 'Иран',
  Iraq: 'Ирак',
  Ireland: 'Ирландия',
  Israel: 'Израиль',
  Italy: 'Италия',
  Jamaica: 'Ямайка',
  Japan: 'Япония',
  Jordan: 'Иордания',
  Kazakhstan: 'Казахстан',
  Kenya: 'Кения',
  Kiribati: 'Кирибати',
  Korea: 'Корея',
  Kuwait: 'Кувейт',
  Kyrgyzstan: 'Киргизия',
  Laos: 'Лаос',
  Latvia: 'Латвия',
  Lebanon: 'Ливан',
  Lesotho: 'Лесото',
  Liberia: 'Либерия',
  Libya: 'Ливия',
  Liechtenstein: 'Лихтенштейн',
  Lithuania: 'Литва',
  Luxembourg: 'Люксембург',
  Madagascar: 'Мадагаскар',
  Malawi: 'Малави',
  Malaysia: 'Малайзия',
  Maldives: 'Мальдивы',
  Mali: 'Мали',
  Malta: 'Мальта',
  'Marshall Islands': 'Маршалловы Острова',
  Mauritania: 'Мавритания',
  Mauritius: 'Маврикий',
  Mexico: 'Мексика',
  Micronesia: 'Микронезия',
  Moldova: 'Молдова',
  Monaco: 'Монако',
  Mongolia: 'Монголия',
  Montenegro: 'Черногория',
  Morocco: 'Марокко',
  Mozambique: 'Мозамбик',
  Myanmar: 'Мьянма',
  Namibia: 'Намибия',
  Nauru: 'Науру',
  Nepal: 'Непал',
  Netherlands: 'Нидерланды',
  'New Zealand': 'Новая Зеландия',
  Nicaragua: 'Никарагуа',
  Niger: 'Нигер',
  Nigeria: 'Нигерия',
  'North Macedonia': 'Северная Македония',
  Norway: 'Норвегия',
  Oman: 'Оман',
  Pakistan: 'Пакистан',
  Palau: 'Палау',
  Panama: 'Панама',
  'Papua New Guinea': 'Папуа — Новая Гвинея',
  Paraguay: 'Парагвай',
  Peru: 'Перу',
  Philippines: 'Филиппины',
  Poland: 'Польша',
  Portugal: 'Португалия',
  Qatar: 'Катар',
  Romania: 'Румыния',
  Russia: 'Россия',
  Rwanda: 'Руанда',
  'Saint Kitts and Nevis': 'Сент-Китс и Невис',
  'Saint Lucia': 'Сент-Люсия',
  'Saint Vincent and the Grenadines': 'Сент-Винсент и Гренадины',
  Samoa: 'Самоа',
  'San Marino': 'Сан-Марино',
  'Sao Tome and Principe': 'Сан-Томе и Принсипи',
  'Saudi Arabia': 'Саудовская Аравия',
  Senegal: 'Сенегал',
  Serbia: 'Сербия',
  Seychelles: 'Сейшелы',
  'Sierra Leone': 'Сьерра-Леоне',
  Singapore: 'Сингапур',
  Slovakia: 'Словакия',
  Slovenia: 'Словения',
  'Solomon Islands': 'Соломоновы Острова',
  Somalia: 'Сомали',
  'South Africa': 'ЮАР',
  'South Korea': 'Южная Корея',
  'South Sudan': 'Южный Судан',
  Spain: 'Испания',
  'Sri Lanka': 'Шри-Ланка',
  Sudan: 'Судан',
  Suriname: 'Суринам',
  Sweden: 'Швеция',
  Switzerland: 'Швейцария',
  Syria: 'Сирия',
  Taiwan: 'Тайвань',
  Tajikistan: 'Таджикистан',
  Tanzania: 'Танзания',
  Thailand: 'Таиланд',
  Togo: 'Того',
  Tonga: 'Тонга',
  'Trinidad and Tobago': 'Тринидад и Тобаго',
  Tunisia: 'Тунис',
  Turkey: 'Турция',
  Turkmenistan: 'Туркмения',
  Tuvalu: 'Тувалу',
  Uganda: 'Уганда',
  Ukraine: 'Украина',
  'United Arab Emirates': 'ОАЭ',
  'United Kingdom': 'Великобритания',
  USA: 'США',
  Uruguay: 'Уругвай',
  Uzbekistan: 'Узбекистан',
  Vanuatu: 'Вануату',
  Venezuela: 'Венесуэла',
  Vietnam: 'Вьетнам',
  Yemen: 'Йемен',
  Zambia: 'Замбия',
  Zimbabwe: 'Зимбабве',
};
